# Generated by Django 3.2.9 on 2021-12-02 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TEAMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='team',
            name='team_id',
            field=models.IntegerField(),
        ),
    ]
